todo/urls.py
from django.urls import path

from todo.views import (
    TaskListView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskToggleView,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
    path("task/create/", TaskCreateView.as_view(), name="task-create"),
    path("task/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("task/<int:pk>/toggle/", TaskToggleView.as_view(), name="task-toggle"),
]

app_name = "todo"

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
]

todo/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ("done", "-created_at", )

    def __str__(self):
        return f"{self.content}: {self.done}"

todo/forms.py
from django import forms
from todo.models import Task, Tag


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )
    deadline = forms.DateTimeField(
        widget=forms.DateInput(attrs={"type": "datetime-local", "class": "form-control"}),
        required=False
    )

    class Meta:
        model = Task
        fields = ["content", "deadline", "done", "tags"]
        widgets = {
            "content": forms.Textarea(attrs={"class": "form-control"}),
            "done": forms.CheckboxInput(attrs={"class": "form-check-input"}),
        }

todo/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic

from todo.forms import TaskForm
from todo.models import Tag, Task


class TaskListView(generic.ListView):
    model = Task
    template_name = "todo/task_list.html"
    context_object_name = "tasks"


class TagListView(generic.ListView):
    model = Tag
    template_name = "todo/tag_list.html"
    context_object_name = "tags"


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    template_name = "todo/task_form.html"
    success_url = reverse_lazy("todo:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    template_name = "todo/task_form.html"
    success_url = reverse_lazy("todo:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    template_name = "todo/task_confirm_delete.html"
    success_url = reverse_lazy("todo:task-list")


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    template_name = "todo/tag_form.html"
    success_url = reverse_lazy("todo:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    template_name = "todo/tag_form.html"
    success_url = reverse_lazy("todo:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    template_name = "todo/tag_confirm_delete.html"
    success_url = reverse_lazy("todo:tag-list")


class TaskToggleView(generic.View):
    @staticmethod
    def get(request, *args, **kwargs):
        task = get_object_or_404(Task, pk=kwargs["pk"])
        task.done = not task.done
        task.save()
        return redirect("todo:task-list")

templates/base.html
<!doctype html>
<html lang="en">
<head>
  <title>Todo App</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
      integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
      crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-3 sidebar-nav list-group">
        <ul>
          <li class="list-group-item">
            <a href="{% url 'todo:task-list' %}">Home</a>
          </li>
          <li class="list-group-item">
            <a href="{% url 'todo:tag-list' %}">Tags</a>
          </li>
        </ul>
      </div>
      <div class="col-sm-9">
        {% block content %}
        {% endblock %}
      </div>
    </div>
  </div>
</body>
</html>

templates/todo/base.html
<!doctype html>
<html lang="en">
<head>
  <title>Todo App</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
      integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
      crossorigin="anonymous">
</head>
<body>
  <div class="sidebar">
        <ul>
            <li><a href="{% url 'todo:task-list' %}">Home</a></li>
            <li><a href="{% url 'todo:tag-list' %}">Tag List</a></li>
        </ul>
    </div>
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete this tag?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'todo:tag-list' %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
<h1>{{ object|yesno:"Edit, New" }} Tag</h1>
  <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <input class="btn btn-primary" type="submit" value="Save">
  </form>
{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Tags 
    <a class="btn btn-primary" style="inline-start: rtl" href="{% url 'todo:tag-create' %}">
      Add
    </a></h1>

  {% if tags %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      {% for tag in tags %}
        <tr>
          <td>
            {{ tag.name }}
          </td>
          <td>
            <a class="btn btn-secondary" href="{% url 'todo:tag-update' pk=tag.id %}">UPDATE</a>
          </td>
          <td>
            <a class="btn btn-secondary" href="{% url 'todo:tag-delete' pk=tag.id %}">DELETE</a>
          </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no tags</p>
  {% endif %}
{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'todo:task-list' %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
<h1>{{ object|yesno:"Edit, New" }} Task</h1>
  <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <input class="btn btn-primary" type="submit" value="Save">
  </form>
{% endblock %}

templates/todo/task_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Todo List
    <a href="{% url 'todo:task-create' %}" class="btn btn-primary" style="inline-start: rtl">
      Add Task
    </a>
  </h1>
  {% for task in tasks %}
    <hr>
    <h5>{{ task.content }}
      {% if task.done %}
        <span style="color: green"><strong>Done</strong></span>
      {% else %}
        <span style="color: red"><strong>Not done</strong></span>
      {% endif %}
      <a href="{% url 'todo:task-toggle' pk=task.id %}" style="float: right">
        {% if task.done %}
          <span class="btn btn-secondary">Undo</span>
        {% else %}
          <span class="btn btn-success">Complete</span>
        {% endif %}
      </a>
    </h5>
    <p>
      Created: {{ task.created_at }}
      {% if task.done %}
      <span style="color: darkred">Deadline: {{ task.deadline }}</span>
      {% endif %}
    </p>
    <h5 class="text-muted">Tags: {% for tag in task.tags.all %} {{ tag.name }} {% endfor %}
      <a href="{% url 'todo:task-update' pk=task.id %}" style="color: dodgerblue">Update</a>
      <a href="{% url 'todo:task-delete' pk=task.id %}" style="color: dodgerblue">Delete</a>
    </h5>
{% endfor %}
{% endblock %}